### ISSUE TITLE
adding feature: gross_income_per_item, using gross_item() function

### ISSUE THREAD

**Issue by yasiwang0315** [dsi-principles-prog/midterm-yasiwang0315#2]
In this step, you'll need to create a new variable called gross_income_per_item to reflect this information. It can be calculated by: total gross income / quantity.

The function should include only one parameter: data frame

Doing the `assert()` function, we need to test whether new variables (numeric) are within 100.

After applying the function to the data, you'll expect to see the following format:
![image](https://user-images.githubusercontent.com/42261801/67698351-34e00880-f978-11e9-8020-5ac01172df84.png)

**Comment by charlieyyy** [comment]
add gross item function
